/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    jobs: Job;
    'job-categories': JobCategory;
    locations: Location;
    services: Service;
    articles: Article;
    'article-categories': ArticleCategory;
    media: Media;
    employers: Employer;
    'recruitment-requests': RecruitmentRequest;
    'page-views': PageView;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-categories': JobCategoriesSelect<false> | JobCategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    employers: EmployersSelect<false> | EmployersSelect<true>;
    'recruitment-requests': RecruitmentRequestsSelect<false> | RecruitmentRequestsSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Jobs without a closing date stop being advertised 30 days after publishing. Closed jobs stay visible (not indexed) for 90 days, then their URL is retired.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * e.g. Restaurant Supervisor
   */
  title: string;
  category: number | JobCategory;
  location: number | Location;
  /**
   * One or two sentences. Used on job cards and as the search-result description.
   */
  summary: string;
  employmentTypes: (
    'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'TEMPORARY' | 'INTERN' | 'VOLUNTEER' | 'PER_DIEM' | 'OTHER'
  )[];
  employerVisibility: 'confidential' | 'named';
  /**
   * Internal record. Only its public name is shown, and only when "Named" is selected.
   */
  employer?: (number | null) | Employer;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Experience expected, only if the employer specified it, e.g. "At least 1 year in a busy restaurant"
   */
  experience?: string | null;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  additionalDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Only publish a salary the employer has confirmed.
   */
  showSalary?: boolean | null;
  salary?: {
    currency?: string | null;
    min?: number | null;
    max?: number | null;
    unit?: ('HOUR' | 'DAY' | 'WEEK' | 'MONTH' | 'YEAR') | null;
    /**
     * e.g. "plus service charge"
     */
    note?: string | null;
  };
  applicationMethod: 'instructions' | 'whatsapp';
  /**
   * Shown on the page and included in search-engine job data.
   */
  applicationInstructions: string;
  /**
   * Draft jobs are saved but NOT shown on the website. Choose "Open" and save to publish.
   */
  status: 'draft' | 'open' | 'closed';
  closeReason?: ('filled' | 'deadline' | 'withdrawn') | null;
  /**
   * Show on the home page while open.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Applications accepted until the end of this day (Kampala time).
   */
  closingDate?: string | null;
  closedAt?: string | null;
  retirement: 'gone' | 'redirect-to-category';
  /**
   * Never shown publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-categories".
 */
export interface JobCategory {
  id: number;
  name: string;
  /**
   * Used in the page URL. Changing it on a published page creates a 301 redirect from the old URL.
   */
  slug: string;
  /**
   * e.g. "Restaurant" sits under "Hospitality".
   */
  parent?: (number | null) | JobCategory;
  /**
   * Genuinely useful introduction for job seekers (what these roles involve, typical requirements). An empty category with no live jobs and no intro is kept out of search results.
   */
  intro?: string | null;
  /**
   * Employer-side service for this job family, linked as "Hiring for these roles?"
   */
  relatedService?: (number | null) | Service;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. Restaurant Staff Recruitment
   */
  title: string;
  /**
   * Used in the page URL. Changing it on a published page creates a 301 redirect from the old URL.
   */
  slug: string;
  /**
   * e.g. Restaurant Staff Recruitment → Hospitality Recruitment
   */
  parent?: (number | null) | Service;
  summary: string;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Job families this service recruits for (cluster links to live vacancies).
   */
  relatedJobCategories?: (number | JobCategory)[] | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows for people who cannot see it. Do not stuff keywords.
   */
  alt: string;
  /**
   * Stock photos are illustrative only. Never caption or place them in a way that implies the people are Job Link staff, candidates or clients, or that a location is our office.
   */
  source: 'unsplash' | 'licensed-stock' | 'job-link';
  /**
   * Photographer name
   */
  creditName?: string | null;
  /**
   * Link to the original photo page
   */
  creditUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * e.g. Kampala
   */
  name: string;
  /**
   * Used in the page URL. Changing it on a published page creates a 301 redirect from the old URL.
   */
  slug: string;
  /**
   * e.g. Central Region
   */
  region?: string | null;
  /**
   * ISO country code. Locked to UG while overseas recruitment is disabled.
   */
  countryCode: string;
  /**
   * Publish a dedicated /locations page. Only enable where Job Link has genuine recruitment activity, to avoid thin doorway pages.
   */
  hasLandingPage?: boolean | null;
  /**
   * Local context for job seekers and employers in this area.
   */
  intro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employers".
 */
export interface Employer {
  id: number;
  /**
   * Internal name.
   */
  name: string;
  /**
   * Name shown on vacancies, only where the employer has agreed to be named.
   */
  publicName?: string | null;
  website?: string | null;
  contactName?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Used in the page URL. Changing it on a published page creates a 301 redirect from the old URL.
   */
  slug: string;
  /**
   * What the reader will get from this article. Used on cards and in search results.
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: (number | null) | ArticleCategory;
  /**
   * A real person who wrote or reviewed the article. Leave empty to credit Job Link Uganda.
   */
  authorName?: string | null;
  publishedAt?: string | null;
  relatedJobCategory?: (number | null) | JobCategory;
  relatedService?: (number | null) | Service;
  primaryCta?: ('jobs' | 'hire-staff' | 'none') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: number;
  name: string;
  /**
   * Used in the page URL. Changing it on a published page creates a 301 redirect from the old URL.
   */
  slug: string;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-requests".
 */
export interface RecruitmentRequest {
  id: number;
  businessName: string;
  contactName: string;
  phone: string;
  email?: string | null;
  location?: string | null;
  rolesNeeded: string;
  numberOfPositions?: number | null;
  preferredStartDate?: string | null;
  message?: string | null;
  serviceSlug?: string | null;
  /**
   * Contact consented to Job Link Uganda processing this enquiry.
   */
  consent: boolean;
  /**
   * Page the enquiry was sent from.
   */
  sourcePath?: string | null;
  status?: ('new' | 'contacted' | 'in-progress' | 'closed') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  path: string;
  jobRef?: string | null;
  visitorId: string;
  referrerHost?: string | null;
  device: 'mobile' | 'tablet' | 'desktop';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown only inside the admin. Never published on the website.
   */
  displayName?: string | null;
  roles: ('admin' | 'recruiter' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'job-categories';
          value: number | JobCategory;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-categories';
        value: number | JobCategory;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: number | ArticleCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'employers';
        value: number | Employer;
      } | null)
    | ({
        relationTo: 'recruitment-requests';
        value: number | RecruitmentRequest;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  location?: T;
  summary?: T;
  employmentTypes?: T;
  employerVisibility?: T;
  employer?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  experience?: T;
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  additionalDetails?: T;
  showSalary?: T;
  salary?:
    | T
    | {
        currency?: T;
        min?: T;
        max?: T;
        unit?: T;
        note?: T;
      };
  applicationMethod?: T;
  applicationInstructions?: T;
  status?: T;
  closeReason?: T;
  featured?: T;
  publishedAt?: T;
  closingDate?: T;
  closedAt?: T;
  retirement?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-categories_select".
 */
export interface JobCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  intro?: T;
  relatedService?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  countryCode?: T;
  hasLandingPage?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  summary?: T;
  featuredImage?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedJobCategories?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  body?: T;
  category?: T;
  authorName?: T;
  publishedAt?: T;
  relatedJobCategory?: T;
  relatedService?: T;
  primaryCta?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  source?: T;
  creditName?: T;
  creditUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employers_select".
 */
export interface EmployersSelect<T extends boolean = true> {
  name?: T;
  publicName?: T;
  website?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-requests_select".
 */
export interface RecruitmentRequestsSelect<T extends boolean = true> {
  businessName?: T;
  contactName?: T;
  phone?: T;
  email?: T;
  location?: T;
  rolesNeeded?: T;
  numberOfPositions?: T;
  preferredStartDate?: T;
  message?: T;
  serviceSlug?: T;
  consent?: T;
  sourcePath?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  jobRef?: T;
  visitorId?: T;
  referrerHost?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details and business information shown across the website. Only enter verified details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * As it should be displayed, e.g. +256 7XX XXX XXX
   */
  phone?: string | null;
  email?: string | null;
  /**
   * Digits only, e.g. 2567XXXXXXXX
   */
  whatsappCandidates?: string | null;
  /**
   * Can be the same number.
   */
  whatsappEmployers?: string | null;
  /**
   * Only tick if there is a verified office that visitors can come to.
   */
  hasPublicOffice?: boolean | null;
  office?: {
    streetAddress?: string | null;
    locality?: string | null;
    region?: string | null;
    postalCode?: string | null;
    /**
     * Google Maps link to the verified location.
     */
    mapUrl?: string | null;
  };
  openingHours?:
    | {
        /**
         * e.g. Mon–Fri 8:30–17:30
         */
        line: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'x' | 'tiktok' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback meta description for pages without their own.
   */
  defaultDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  whatsappCandidates?: T;
  whatsappEmployers?: T;
  hasPublicOffice?: T;
  office?:
    | T
    | {
        streetAddress?: T;
        locality?: T;
        region?: T;
        postalCode?: T;
        mapUrl?: T;
      };
  openingHours?:
    | T
    | {
        line?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}